apiVersion: v2
name: apicurio
version: 2.46.0-beta
description: API design studio
type: application
keywords:
  - api
home: http://www.apicur.io/
sources:
  - https://github.com/Apicurio/apicurio-studio

