
{{- if .Values.database.install }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    module: {{ .Values.database.name }}
  name: {{ .Values.database.name }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      module: {{ .Values.database.name }}
  template:
    metadata:
      labels:
        module: {{ .Values.database.name }}
    spec:
      containers:
        - name: {{ .Values.database.name }}
          args:
            - --default-authentication-plugin=mysql_native_password
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
            - --ignore-db-dir=lost+found
          env:
            - name: MYSQL_DATABASE
              value: {{ .Values.database.schema }}
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "apicurio-studio.secretName" . }}
                  key: db-password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "apicurio-studio.secretName" . }}
                  key: db-root-password
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "apicurio-studio.secretName" . }}
                  key: db-user
          image: {{ .Values.database.image }}
          imagePullPolicy: {{ .Values.database.imagePullPolicy }}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-apicurio
            {{- range $volume := .Values.database.extraVolumes }}
            - mountPath: {{ $volume.mountPath | quote }}
              name: {{ $volume.name | quote }}
            {{- end }}
      restartPolicy: Always
      volumes:
        - name: mysql-apicurio
          persistentVolumeClaim:
            claimName: apicuriodata
        {{- range $volume := .Values.database.extraVolumes }}
        - name: {{ $volume.name | quote }}
          {{- $volume.volume | toYaml | nindent 10 }}
        {{- end }}
      securityContext:
        fsGroup: 999
{{- end }}